server:
  port: 8081

spring:
  application:
    name: transaction-service
  datasource:
    url: jdbc:h2:mem:txdb
  jpa:
    hibernate:
      ddl-auto: create-drop
  rabbitmq:
    host: localhost
    port: 15672

eureka:
  client:
    service-url:
        defaultZone: http://localhost:8761/eureka/

management:
    endpoints:
        web:
            exposure:
                include: "*"